<?php

if (!\defined('TOLVIGNETTEN_PATH')) {
    \define('TOLVIGNETTEN_PATH', \plugin_dir_path(__FILE__));
}

if (!\defined('TOLVIGNETTEN_DEFAULT_LOCALE')) {
    \define('TOLVIGNETTEN_DEFAULT_LOCALE', 'nl_NL');
}

if (!\defined('TOLVIGNETTEN_MAP_SHORCODE')) {
    \define('TOLVIGNETTEN_MAP_SHORCODE', 'tolvignetten_map');
}

if (!\defined('TOLVIGNETTEN_STORE_SHORCODE')) {
    \define('TOLVIGNETTEN_STORE_SHORCODE', 'tolvignetten_store');
}

if (!\defined('TOLVIGNETTEN_STORE_CART_BUTTON_SHORCODE')) {
    \define('TOLVIGNETTEN_STORE_CART_BUTTON_SHORCODE', 'tolvignetten_store_cart_button');
}

if (!\defined('TOLVIGNETTEN_STORE_DEFAULT_URL')) {
    if (false !== \getenv('TOLVIGNETTEN_STORE_DEFAULT_URL')) {
        \define('TOLVIGNETTEN_STORE_DEFAULT_URL', \getenv('TOLVIGNETTEN_STORE_DEFAULT_URL'));
    } else {
        \define('TOLVIGNETTEN_STORE_DEFAULT_URL', 'https://ui.tolvignetten.nl');
    }
}

if (!\defined('TOLVIGNETTEN_UI_SID_COOKIE_NAME')) {
    \define('TOLVIGNETTEN_UI_SID_COOKIE_NAME', 'prod_ui_sid');
}

if (!\defined('TOLVIGNETTEN_UI_QUERY_COOKIE_NAME')) {
    \define('TOLVIGNETTEN_UI_QUERY_COOKIE_NAME', 'prod_ui_query');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_COOKIE_NAME')) {
    \define('TOLVIGNETTEN_AFFILIATE_COOKIE_NAME', 'tolvignetten_affiliate_storage');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_COOKIE_DURATION_DAYS')) {
    \define('TOLVIGNETTEN_AFFILIATE_COOKIE_DURATION_DAYS', 30);
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_COOKIE_PATH')) {
    \define('TOLVIGNETTEN_AFFILIATE_COOKIE_PATH', '/');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_CSS_SELECTOR_PRIMARY_COLOR_TEXT')) {
    \define('TOLVIGNETTEN_AFFILIATE_CSS_SELECTOR_PRIMARY_COLOR_TEXT', '.ta-primary-color-text');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_CSS_SELECTOR_PRIMARY_COLOR_BG')) {
    \define('TOLVIGNETTEN_AFFILIATE_CSS_SELECTOR_PRIMARY_COLOR_BG', '.ta-primary-color-bg');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_CSS_SELECTOR_SECONDARY_COLOR_TEXT')) {
    \define('TOLVIGNETTEN_AFFILIATE_CSS_SELECTOR_SECONDARY_COLOR_TEXT', '.ta-secondary-color-text');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_CSS_SELECTOR_SECONDARY_COLOR_BG')) {
    \define('TOLVIGNETTEN_AFFILIATE_CSS_SELECTOR_SECONDARY_COLOR_BG', '.ta-secondary-color-bg');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_PARTNER_ID_PARAM_NAME')) {
    \define('TOLVIGNETTEN_AFFILIATE_PARTNER_ID_PARAM_NAME', 'partner_id');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_PARTNER_INFO_PARAM_NAME_OLD')) {
    \define('TOLVIGNETTEN_AFFILIATE_PARTNER_INFO_PARAM_NAME_OLD', 'pi');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_PARTNER_INFO_PARAM_NAME')) {
    \define('TOLVIGNETTEN_AFFILIATE_PARTNER_INFO_PARAM_NAME', 'partner_info');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_PARTNER_ANVR_PARAM_NAME')) {
    \define('TOLVIGNETTEN_AFFILIATE_PARTNER_ANVR_PARAM_NAME', 'anvr');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_PARTNER_BDR_PARAM_NAME')) {
    \define('TOLVIGNETTEN_AFFILIATE_PARTNER_BDR_PARAM_NAME', 'bdr');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_COOKIE_PARTNER_ID')) {
    \define('TOLVIGNETTEN_AFFILIATE_COOKIE_PARTNER_ID', \TOLVIGNETTEN_AFFILIATE_PARTNER_ID_PARAM_NAME);
}

if (!\defined('TOLVIGNETTEN_PLUGIN_VERSION_COOKIE_NAME')) {
    \define('TOLVIGNETTEN_PLUGIN_VERSION_COOKIE_NAME', 'tolvignetten_v');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_LICENSE_PLATE_NUMBER_PARAM_NAME')) {
    \define('TOLVIGNETTEN_AFFILIATE_LICENSE_PLATE_NUMBER_PARAM_NAME', 'licensePlateNumber');
}

if (!\defined('TOLVIGNETTEN_GOOGLE_MAPS_API_KEY')) {
    \define('TOLVIGNETTEN_GOOGLE_MAPS_API_KEY', 'AIzaSyCOESH_Dq-5yMqW2dZvorjBGbRmHx5k_40');
}

if (!\defined('TOLVIGNETTEN_GOOGLE_MAPS_PUBLIC_API_KEY')) {
    \define('TOLVIGNETTEN_GOOGLE_MAPS_PUBLIC_API_KEY', 'AIzaSyC8w-9bX7N_ygFXi8tS-gKFcvZDMGQvjYg');
}

if (!\defined('TOLVIGNETTEN_REFRESH_URL_SEGMENT')) {
    \define('TOLVIGNETTEN_REFRESH_URL_SEGMENT', 'ta-session-refresh');
}

if (!\defined('TOLVIGNETTEN_REFRESH_PARAM_NAME')) {
    \define('TOLVIGNETTEN_REFRESH_PARAM_NAME', '_ta_ref');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_COOKIE_KEY_INFO')) {
    \define('TOLVIGNETTEN_AFFILIATE_COOKIE_KEY_INFO', '_info');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_COOKIE_KEY_ANVR')) {
    \define('TOLVIGNETTEN_AFFILIATE_COOKIE_KEY_ANVR', '_anvr');
}

if (!\defined('TOLVIGNETTEN_AFFILIATE_COOKIE_KEY_BDR')) {
    \define('TOLVIGNETTEN_AFFILIATE_COOKIE_KEY_BDR', '_bdr');
}

if (!\defined('TOLVIGNETTEN_REQUEST_DEFAULT_TIMEOUT')) {
    \define('TOLVIGNETTEN_REQUEST_DEFAULT_TIMEOUT', 60000);
}
